auth_token: set correct charset when replying with 401
The Content-Type header does not contain the charset used for the
message. It's now required by webob:

  File "/home/jenkins/workspace/gate-gnocchi-tox-db-py35-mysql-ubuntu-xenial/.tox/py35-mysql/lib/python3.5/site-packages/keystonemiddleware/auth_token/__init__.py", line 331, in __call__
    response = self.process_request(req)
  File "/home/jenkins/workspace/gate-gnocchi-tox-db-py35-mysql-ubuntu-xenial/.tox/py35-mysql/lib/python3.5/site-packages/keystonemiddleware/auth_token/__init__.py", line 650, in process_request
    content_type='application/json')
  File "/home/jenkins/workspace/gate-gnocchi-tox-db-py35-mysql-ubuntu-xenial/.tox/py35-mysql/lib/python3.5/site-packages/webob/exc.py", line 268, in __init__'
    **kw)
  File "/home/jenkins/workspace/gate-gnocchi-tox-db-py35-mysql-ubuntu-xenial/.tox/py35-mysql/lib/python3.5/site-packages/webob/response.py", line 310, in __init__'
    "You cannot set the body to a text value without a "
TypeError: You cannot set the body to a text value without a charset

Change-Id: Ia6c667c9afcba0811f51f3e50f34de05310d1433